import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import axios from 'axios';

const url = 'https://api.lichi.com/';


export default function Home() {
  // функция для добавления товара в корзину
   function addToCart(event) {
    document.cookie = 'SID=SID.16776900501031.7314273-0;';
    const credential = document.cookie;
    let product = event.target.id;
    console.log(product);

     axios
      .post(url + `cart/add?lang=1&shop=1&id=${product}`, {
        withCredentials: true,
        credential,
        headers: {
          'Access-Control-Allow-Origin': 'https://api.lichi.com',
          'Content-Type': 'text/html',
        },
      })
      .then((response) => {
        console.log(response);
        localStorage.setItem('id', product)
      })
      .catch((error) => {
        console.error(error);
      });
  }

  // функция для получения товаров, добавленных в корзину
   function showCart(event) {
    document.cookie = 'SID=SID.16776900501031.7314273-0;';
    let product = localStorage.getItem('id');
     axios
      .get(`https://api.lichi.com/cart/list?shop=1&lang=1&id=${product}`)
      .then((item) => {
        console.log(item.data.api_data);
        item.data.api_data.aData = [
          (item = product),
          (item = 'Легкая блуза с воланом на воротнике'),
        ];
      })
      .catch((error) => {
        console.error(error);
      });
  }

  function deleteProduct(event) {
    axios
      .delete(url + `cart/remove?lang=1&shop=1&id=${event.target.id}&all=false`)
      .then((res) => {
        console.log(res);
        
      })
      .catch((error) => {
        console.error(error);
      });
  }

  function deleteAllProduct(event) {
    axios
      .delete(url + `cart/remove?lang=1&shop1&id=${event.target.id}&all=true`)
      .then((res) => {
        console.log(res);
      })
      .catch((error) => {
        console.error(error);
      });
  }

  return (
    <>
      <Head>
        <title>Lichi tz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: "flex",
        flexDirection: "column",
        marginTop: 50,
        marginBottom: 80
    }}>
        <h1 className={styles.name}>Cart</h1>
        <button onClick={addToCart} className={styles.product} id="94267">
          Купить блузу
        </button>
        <button onClick={addToCart} className={styles.product} id="94268">
          Купить платье
        </button>
        <button onClick={addToCart} className={styles.product} id="94269">
          Купить юбку
        </button>

        <button type="button" onClick={showCart} className={styles.show} id="94267">
          Открыть корзину
        </button>
        <button type="button" onClick={deleteProduct} className={styles.delete} id="94267">
          Убрать продукт
        </button>
        <button type="button" onClick={deleteAllProduct} className={styles.delete} id="94267">
          Убрать все продукты
        </button>
      </div>
    </>
  );
}
