import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from 'axios';

export default function Home() {

 function addToCart () {
    let url = 'https://api.lichi.com/cart/';
    document.cookie = "SID=SID.16776900501031.7314273-0;";
    const credential = document.cookie
    console.log(credential);    
    const res =  axios.post( url + 'add?lang=1&shop=1&id=44546', {
      withCredentials: true,
      credential,
      headers: {'Access-Control-Allow-Origin': 'https://api.lichi.com/', 'Content-Type': 'application/x-www-form-urlencoded'},
    })
    console.log(res);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1>Hello</h1>
       <button onClick={addToCart}>Add to cart</button>

      </main>
    </>
  )
}
